### ISSUE TITLE
nice addon

### ISSUE THREAD

**Issue by cizas1** [septimun/sNamePlates#1]
hi, nice addon bro, one question,  How can I move the casting bar a little more to the left? 

https://cdn.discordapp.com/attachments/711417835016159343/1244332557148098630/WoWScrnShot_052624_135028.jpg?ex=6654ba80&is=66536900&hm=6d7dcc82681a2507ba32bce4000d61c4f6f76cf85c727db0df6b30fa48627369&

**Comment by antmonsep** [comment]
Hello! Thanks for using the addon. I just fixed the issue: basically it skins the default cast bar that the game has, but even if you tell the cast bar to be in a specific spot, it will not do it (old game things) and that's why you saw it not being close to the actual cast bar. Now it should work, redownload the addon. Thanks again for raising this

**Comment by cizas1** [comment]
i love ur addon bro, u can fix muchs options, i have one ideas.

https://cdn.discordapp.com/attachments/711417835016159343/1244805722558955642/WoWScrnShot_052724_205357.jpg?ex=6656732b&is=665521ab&hm=898b7550c1f06b4aeda77682a42a4dca94d2d6446a15ba9fb24bab6b280029c9&

how u can activate colission? like this 

https://cdn.discordapp.com/attachments/711417835016159343/1244806702180732988/WoWScrnShot_052724_211442.jpg?ex=66567415&is=66552295&hm=70de3fb3f1ff170794b30d03db961070f1a3ad122f350b665b477ecf2a89ef86&

(this is TidyPlates)

but ur addon is rly good, 
I would like to use it for 3v3.

I would also like an option to shrink or enlarge the cast icon

sry for my english xD

**Comment by antmonsep** [comment]
hello again! well, I actually don't know how to approach this, look at this
![image](https://github.com/antmonsep/sNamePlates/assets/69049114/b1c4f05a-34c9-4fd9-84e6-d1b98dbefc79)
This addon sort of changes the appearence of the classic nameplates, so it inherits their behaviour when overlapped like you can see on the top images. The max I could do for you is to avoid the border to show on top of any healthbar like you can see on image number 3. How to do so? 
1. you'll have to open `core.lua` file inside the sNamePlates folder with any code editor
2. find this line in the file `frame.hpGlow = CreateFrame("Frame", nil, frame.healthbar)`
3. then you will paste this code below the one found in step 2. `frame.hpGlow:SetFrameLevel(frame.healthbar:GetFrameLevel() - 1)`, 
just like this:
![image](https://github.com/antmonsep/sNamePlates/assets/69049114/42ae5b4e-7e9c-49b5-97c3-20594e3632a4)
4. save the changes in `core.lua`, and finally
5. /reload ingame, and you should be able to see a change

Regarding your second comment, I just pushed a new change to handle castbar icon, more than welcome to check it out.
Cheers

**Comment by cizas1** [comment]
I already updated it and it was just what I wanted, thanks for everything, I have more ideas if you want? xd
